spring:
  datasource:
    url: jdbc:h2:file:/data/jinvest
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
       hibernate:
         default_schema: "JINVEST"
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
